### ISSUE TITLE
Add parameter space mathematical operator wrappers

### ISSUE THREAD

**Issue by salamanders** [deeplearning4j/Arbiter#123]
#### FR: Demonstrate how to do correlated hyperparameter tuning

[This example](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/kotlin/org/deeplearning4j/examples/feedforward/mnist/MLPMnistTwoLayerExample.kt) shows `.regularization(true).l2(rate * 0.005) // regularize learning model`

But when trying to use Arbiter to tune the learning `rate`, how would you do this sort of correlated parameter tuning?  It wouldn't work to do

    val learningRateHyperparam = ContinuousParameterSpace(0.0001, 0.1)
    ....
    .l2(learningRateHyperparam * 0.005)

but that is the pseudocode of what I'm trying to accomplish.

FR: show in the docs how to code this.  (or if not possible, then the FR is to be able to do it)

**Comment by AlexDBlack** [comment]
I was under the impression that we already has this functionality, but apparently not.
It shouldn't be too hard to add - we'd just need a parameter space that wraps an existing continuous parameter space, and applies a mathematical operation (such as 'multiply by fixed scalar' in your case) in the getValue.
If you want to try implementing this, great (I'd love a pull request). Otherwise I'll try to look at it when I have time.

**Comment by AlexDBlack** [comment]
Added here - https://github.com/deeplearning4j/Arbiter/pull/142
@salamanders thanks for the issue
See unit tests in the PR above on how to use.
